import tkinter
from tkinter import *
from tkinter import messagebox
t=tkinter.Tk()
t.geometry('1800x1200')
def logout():
    t.destroy()
def insert1():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        sql="insert into itemcategory values('%s','%s','%s')"%(p,q,r)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        x.close()
    l1=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=850,y=210)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1050,y=215)
    l2=Label(t,text='Category Name',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=850,y=260)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1050,y=265)
    l3=Label(t,text='Description',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=850,y=310)
    e3=Entry(t,width=60,bg='orange')
    e3.place(x=1050,y=315)
    b1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert1)
    b1.place(x=1050,y=380)   
def find1():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select categoryName,Description from itemcategory where ItemCategoryID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        x.close()
    def reset():
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
    l1=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=850,y=210)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1050,y=215)
    l2=Label(t,text='Category Name',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=850,y=260)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1050,y=265)
    l3=Label(t,text='Description',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=850,y=310)
    e3=Entry(t,width=60,bg='orange')
    e3.place(x=1050,y=315)
    b2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b2.place(x=1000,y=360)
    b3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    b3.place(x=1100,y=360)
def update1():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        sql="update itemcategory set categoryName='%s',Description='%s' where itemcategoryID='%s'"%(q,r,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select categoryName,Description from itemcategory where ItemCategoryID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        x.close()
    l1=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=850,y=210)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1050,y=215)
    l2=Label(t,text='Category Name',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=850,y=260)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1050,y=265)
    l3=Label(t,text='Description',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=850,y=310)
    e3=Entry(t,width=60,bg='orange')
    e3.place(x=1050,y=315)
    b4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b4.place(x=1300,y=200)
    b5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    b5.place(x=1030,y=370)
def delete1():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="delete from itemcategory where ItemCategoryID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        e1.delete(0,100)
        x.close()
    l1=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=290)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1110,y=295)
    b6=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    b6.place(x=1050,y=360)
def insert2():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=n1.get()
        q=n2.get()
        r=n3.get()
        s=n4.get()
        t=int(n5.get())
        u=int(n6.get())
        v=int(n7.get())
        sql="insert into item values('%s','%s','%s','%s',%d,%d,%d)"%(p,q,r,s,t,u,v)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        n1.delete(0,100)
        n2.delete(0,100)
        n3.delete(0,100)
        n4.delete(0,100)
        n5.delete(0,100)
        n6.delete(0,100)
        n7.delete(0,100)
        x.close()
    m1=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    m1.place(x=900,y=150)
    n1=Entry(t,width=30,bg='orange')
    n1.place(x=1150,y=155)
    m2=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    m2.place(x=900,y=200)
    n2=Entry(t,width=30,bg='orange')
    n2.place(x=1150,y=205)
    m3=Label(t,text='Item Name',fg='black',font=('Elephant',15),bg='white')
    m3.place(x=900,y=250)
    n3=Entry(t,width=30,bg='orange')
    n3.place(x=1150,y=255)
    m4=Label(t,text='Unit',fg='black',font=('Elephant',15),bg='white')
    m4.place(x=900,y=300)
    n4=Entry(t,width=30,bg='orange')
    n4.place(x=1150,y=303)
    m5=Label(t,text='Price per piece',fg='black',font=('Elephant',15),bg='white')
    m5.place(x=900,y=350)
    n5=Entry(t,width=30,bg='orange')
    n5.place(x=1150,y=350)
    m6=Label(t,text='Open Quantity',fg='black',font=('Elephant',15),bg='white')
    m6.place(x=900,y=406)
    n6=Entry(t,width=30,bg='orange')
    n6.place(x=1150,y=401)
    m7=Label(t,text='Current Quantity',fg='black',font=('Elephant',15),bg='white')
    m7.place(x=900,y=456)
    n7=Entry(t,width=30,bg='orange')
    n7.place(x=1150,y=451)
    o1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert)
    o1.place(x=1100,y=520)
def find2():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=n1.get()
        sql="select ItemCategoryID,Item_Name,Unit,Price_per_piece,Open_Qty,Current_Qty from item where Item_ID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        n2.insert(0,data[0])
        n3.insert(0,data[1])
        n4.insert(0,data[2])
        n5.insert(0,str(data[3]))
        n6.insert(0,str(data[4]))
        n7.insert(0,str(data[5]))
        x.close()
    def reset():
        n1.delete(0,100)
        n2.delete(0,100)
        n3.delete(0,100)
        n4.delete(0,100)
        n5.delete(0,100)
        n6.delete(0,100)
        n7.delete(0,100)
    m1=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    m1.place(x=900,y=150)
    n1=Entry(t,width=30,bg='orange')
    n1.place(x=1150,y=155)
    m2=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    m2.place(x=900,y=200)
    n2=Entry(t,width=30,bg='orange')
    n2.place(x=1150,y=205)
    m3=Label(t,text='Item Name',fg='black',font=('Elephant',15),bg='white')
    m3.place(x=900,y=250)
    n3=Entry(t,width=30,bg='orange')
    n3.place(x=1150,y=255)
    m4=Label(t,text='Unit',fg='black',font=('Elephant',15),bg='white')
    m4.place(x=900,y=300)
    n4=Entry(t,width=30,bg='orange')
    n4.place(x=1150,y=303)
    m5=Label(t,text='Price per piece',fg='black',font=('Elephant',15),bg='white')
    m5.place(x=900,y=350)
    n5=Entry(t,width=30,bg='orange')
    n5.place(x=1150,y=350)
    m6=Label(t,text='Open Quantity',fg='black',font=('Elephant',15),bg='white')
    m6.place(x=900,y=406)
    n6=Entry(t,width=30,bg='orange')
    n6.place(x=1150,y=401)
    m7=Label(t,text='Current Quantity',fg='black',font=('Elephant',15),bg='white')
    m7.place(x=900,y=456)
    n7=Entry(t,width=30,bg='orange')
    n7.place(x=1150,y=451)
    o2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    o2.place(x=1030,y=520)
    o3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    o3.place(x=1130,y=520)
def update2():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=n1.get()
        q=n2.get()
        r=n3.get()
        s=n4.get()
        t=int(n5.get())
        u=int(n6.get())
        v=int(n7.get())
        sql="update item set ItemCategoryID='%s',Item_Name='%s',Unit='%s',Price_per_piece=%d,Open_Qty=%d,Current_Qty=%d where item_ID='%s'"%(q,r,s,t,u,v,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        n1.delete(0,100)
        n2.delete(0,100)
        n3.delete(0,100)
        n4.delete(0,100)
        n5.delete(0,100)
        n6.delete(0,100)
        n7.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=n1.get()
        sql="select ItemCategoryID,Item_Name,Unit,Price_per_piece,Open_Qty,Current_Qty from item where Item_ID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        n2.insert(0,data[0])
        n3.insert(0,data[1])
        n4.insert(0,data[2])
        n5.insert(0,str(data[3]))
        n6.insert(0,str(data[4]))
        n7.insert(0,str(data[5]))
        x.close()
    m1=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    m1.place(x=900,y=150)
    n1=Entry(t,width=30,bg='orange')
    n1.place(x=1150,y=155)
    m2=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    m2.place(x=900,y=200)
    n2=Entry(t,width=30,bg='orange')
    n2.place(x=1150,y=205)
    m3=Label(t,text='Item Name',fg='black',font=('Elephant',15),bg='white')
    m3.place(x=900,y=250)
    n3=Entry(t,width=30,bg='orange')
    n3.place(x=1150,y=255)
    m4=Label(t,text='Unit',fg='black',font=('Elephant',15),bg='white')
    m4.place(x=900,y=300)
    n4=Entry(t,width=30,bg='orange')
    n4.place(x=1150,y=303)
    m5=Label(t,text='Price per piece',fg='black',font=('Elephant',15),bg='white')
    m5.place(x=900,y=350)
    n5=Entry(t,width=30,bg='orange')
    n5.place(x=1150,y=350)
    m6=Label(t,text='Open Quantity',fg='black',font=('Elephant',15),bg='white')
    m6.place(x=900,y=406)
    n6=Entry(t,width=30,bg='orange')
    n6.place(x=1150,y=401)
    m7=Label(t,text='Current Quantity',fg='black',font=('Elephant',15),bg='white')
    m7.place(x=900,y=456)
    n7=Entry(t,width=30,bg='orange')
    n7.place(x=1150,y=451)
    o4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    o4.place(x=1360,y=135)
    o5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    o5.place(x=1080,y=510)
def delete2():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=n1.get()
        sql="delete from item where Item_ID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        n1.delete(0,100)
        x.close()
    m1=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    m1.place(x=950,y=290)
    n1=Entry(t,width=30,bg='orange')
    n1.place(x=1080,y=295)
    o6=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    o6.place(x=1050,y=350)
def insert3():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=r1.get()
        q=r2.get()
        r=r3.get()
        s=r4.get()
        t=int(r5.get())
        sql="insert into stockin values('%s','%s','%s','%s',%d)"%(p,q,r,s,t)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        r1.delete(0,100)
        r2.delete(0,100)
        r3.delete(0,100)
        r4.delete(0,100)
        r5.delete(0,100)
        x.close()
    q1=Label(t,text='Stock ID',fg='black',font=('Elephant',15),bg='white')
    q1.place(x=900,y=150)
    r1=Entry(t,width=30,bg='orange')
    r1.place(x=1150,y=155)
    q2=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    q2.place(x=900,y=200)
    r2=Entry(t,width=30,bg='orange')
    r2.place(x=1150,y=205)
    q3=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    q3.place(x=900,y=250)
    r3=Entry(t,width=30,bg='orange')
    r3.place(x=1150,y=255)
    q4=Label(t,text='Date Of Entry',fg='black',font=('Elephant',15),bg='white')
    q4.place(x=900,y=300)
    r4=Entry(t,width=30,bg='orange')
    r4.place(x=1150,y=305)
    q5=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    q5.place(x=900,y=350)
    r5=Entry(t,width=30,bg='orange')
    r5.place(x=1150,y=355)
    p1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert)
    p1.place(x=1080,y=420)
def find3():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=r1.get()
        sql="select Item_ID,ItemCategoryID,Date_In,Quantity from stockin where StockID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        r2.insert(0,data[0])
        r3.insert(0,data[1])
        r4.insert(0,data[2])
        r5.insert(0,str(data[3]))
        x.close()
    def reset():
        r1.delete(0,100)
        r2.delete(0,100)
        r3.delete(0,100)
        r4.delete(0,100)
        r5.delete(0,100)
    q1=Label(t,text='Stock ID',fg='black',font=('Elephant',15),bg='white')
    q1.place(x=900,y=150)
    r1=Entry(t,width=30,bg='orange')
    r1.place(x=1150,y=155)
    q2=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    q2.place(x=900,y=200)
    r2=Entry(t,width=30,bg='orange')
    r2.place(x=1150,y=205)
    q3=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    q3.place(x=900,y=250)
    r3=Entry(t,width=30,bg='orange')
    r3.place(x=1150,y=255)
    q4=Label(t,text='Date Of Entry',fg='black',font=('Elephant',15),bg='white')
    q4.place(x=900,y=300)
    r4=Entry(t,width=30,bg='orange')
    r4.place(x=1150,y=305)
    q5=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    q5.place(x=900,y=350)
    r5=Entry(t,width=30,bg='orange')
    r5.place(x=1150,y=355)
    p2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    p2.place(x=1050,y=400)
    p3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    p3.place(x=1150,y=400)
def update3():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=r1.get()
        q=r2.get()
        r=r3.get()
        s=r4.get()
        t=int(r5.get())
        sql="update stockin set Item_ID='%s',ItemCategoryID='%s',Date_In='%s',Quantity=%d where stockID='%s'"%(q,r,s,t,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        r1.delete(0,100)
        r2.delete(0,100)
        r3.delete(0,100)
        r4.delete(0,100)
        r5.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=r1.get()
        sql="select Item_ID,ItemCategoryID,Date_In,Quantity from stockin where StockID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        r2.insert(0,data[0])
        r3.insert(0,data[1])
        r4.insert(0,data[2])
        r5.insert(0,str(data[3]))
        x.close()
    q1=Label(t,text='Stock ID',fg='black',font=('Elephant',15),bg='white')
    q1.place(x=900,y=150)
    r1=Entry(t,width=30,bg='orange')
    r1.place(x=1150,y=155)
    q2=Label(t,text='Item ID',fg='black',font=('Elephant',15),bg='white')
    q2.place(x=900,y=200)
    r2=Entry(t,width=30,bg='orange')
    r2.place(x=1150,y=205)
    q3=Label(t,text='Item Category ID',fg='black',font=('Elephant',15),bg='white')
    q3.place(x=900,y=250)
    r3=Entry(t,width=30,bg='orange')
    r3.place(x=1150,y=255)
    q4=Label(t,text='Date Of Entry',fg='black',font=('Elephant',15),bg='white')
    q4.place(x=900,y=300)
    r4=Entry(t,width=30,bg='orange')
    r4.place(x=1150,y=305)
    q5=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    q5.place(x=900,y=350)
    r5=Entry(t,width=30,bg='orange')
    r5.place(x=1150,y=355)
    p4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    p4.place(x=1360,y=135)
    p5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    p5.place(x=1055,y=420)
def delete3():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=r1.get()
        sql="delete from stockin where StockID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        r1.delete(0,100)
        x.close()
    q1=Label(t,text='Stock ID',fg='black',font=('Elephant',15),bg='white')
    q1.place(x=950,y=290)
    r1=Entry(t,width=30,bg='orange')
    r1.place(x=1080,y=295)
    p6=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    p6.place(x=1050,y=350)
x1=Label(t,text='Item Category',fg='black',font=('Elephant',15),bg='orange')
def insert4():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        s=int(e4.get())
        t=e5.get()
        u=e6.get()
        sql="insert into customers values('%s','%s','%s',%d,'%s','%s')"%(p,q,r,s,t,u)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        x.close()
    l1=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=205)
    l2=Label(t,text='Customer Name',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1100,y=255)
    l3=Label(t,text='Customer Email',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=40,bg='orange')
    e3.place(x=1100,y=305)
    l4=Label(t,text='Customer Phone',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1100,y=355)
    l5=Label(t,text='Customer Address',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=50,bg='orange')
    e5.place(x=1100,y=405)
    l6=Label(t,text='Customer City',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=20,bg='orange')
    e6.place(x=1100,y=455)
    b1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert)
    b1.place(x=1090,y=510)
def find4():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Customer_Name,Customer_Email,Customer_Phone,Customer_Address,Customer_City from customers where Customer_ID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,str(data[2]))
        e5.insert(0,data[3])
        e6.insert(0,data[4])
        x.close()
    def reset():
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
    l1=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=205)
    l2=Label(t,text='Customer Name',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1100,y=255)
    l3=Label(t,text='Customer Email',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=40,bg='orange')
    e3.place(x=1100,y=305)
    l4=Label(t,text='Customer Phone',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1100,y=355)
    l5=Label(t,text='Customer Address',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=50,bg='orange')
    e5.place(x=1100,y=405)
    l6=Label(t,text='Customer City',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=20,bg='orange')
    e6.place(x=1100,y=455)
    b2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b2.place(x=1050,y=500)
    b3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    b3.place(x=1150,y=500)
def update4():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        s=int(e4.get())
        t=e5.get()
        u=e6.get()
        sql="update customers set Customer_Name='%s',Customer_Email='%s',Customer_Phone=%d,Customer_Address='%s',Customer_City='%s' where Customer_ID='%s'"%(q,r,s,t,u,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Customer_Name,Customer_Email,Customer_Phone,Customer_Address,Customer_City from customers where Customer_ID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,str(data[2]))
        e5.insert(0,data[3])
        e6.insert(0,data[4])
        x.close()
    def reset():
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
    l1=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=205)
    l2=Label(t,text='Customer Name',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1100,y=255)
    l3=Label(t,text='Customer Email',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=40,bg='orange')
    e3.place(x=1100,y=305)
    l4=Label(t,text='Customer Phone',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1100,y=355)
    l5=Label(t,text='Customer Address',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=50,bg='orange')
    e5.place(x=1100,y=405)
    l6=Label(t,text='Customer City',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=20,bg='orange')
    e6.place(x=1100,y=455)
    b4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b4.place(x=1350,y=200)
    b5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    b5.place(x=1030,y=500)
    b6=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    b6.place(x=1150,y=500)
def delete4():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="delete from customers where Customer_ID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        e1.delete(0,100)
        x.close()
    l1=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=950,y=290)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=295)
    b7=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    b7.place(x=1050,y=350)
def insert5():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        w=e4.get()
        t=e5.get()
        u=int(e6.get())
        sql="insert into orders values('%s','%s','%s','%s','%s',%d)"%(p,q,r,w,t,u)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        x.close()
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=205)
    l2=Label(t,text='Customer Id',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1100,y=255)
    l3=Label(t,text='Item Id',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1100,y=305)
    l4=Label(t,text='Item Category Id',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1100,y=355)
    l5=Label(t,text='Date Of Order',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=30,bg='orange')
    e5.place(x=1100,y=405)
    l6=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=30,bg='orange')
    e6.place(x=1100,y=455)
    b1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert)
    b1.place(x=1090,y=510)
def find5():
        import pymysql
        c=Canvas(t,width=700,height=600,bg='white')
        c.place(x=770,y=60)
        def find():
            x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
            y=x.cursor()
            p=e1.get()
            sql="select Customer_ID,Item_ID,ItemCategoryID,Date_Order,Qty from orders where OrderID='%s'"%(p)
            y.execute(sql)
            data=y.fetchone()
            e2.insert(0,data[0])
            e3.insert(0,data[1])
            e4.insert(0,data[2])
            e5.insert(0,str(data[3]))
            e6.insert(0,str(data[4]))
            x.close()
        def reset():
            e1.delete(0,100)
            e2.delete(0,100)
            e3.delete(0,100)
            e4.delete(0,100)
            e5.delete(0,100)
            e6.delete(0,100)
        l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
        l1.place(x=900,y=200)
        e1=Entry(t,width=30,bg='orange')
        e1.place(x=1100,y=205)
        l2=Label(t,text='Customer Id',fg='black',font=('Elephant',15),bg='white')
        l2.place(x=900,y=250)
        e2=Entry(t,width=30,bg='orange')
        e2.place(x=1100,y=255)
        l3=Label(t,text='Item Id',fg='black',font=('Elephant',15),bg='white')
        l3.place(x=900,y=300)
        e3=Entry(t,width=30,bg='orange')
        e3.place(x=1100,y=305)
        l4=Label(t,text='Item Category Id',fg='black',font=('Elephant',15),bg='white')
        l4.place(x=900,y=350)
        e4=Entry(t,width=30,bg='orange')
        e4.place(x=1100,y=355)
        l5=Label(t,text='Date Of Order',fg='black',font=('Elephant',15),bg='white')
        l5.place(x=900,y=400)
        e5=Entry(t,width=30,bg='orange')
        e5.place(x=1100,y=405)
        l6=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
        l6.place(x=900,y=450)
        e6=Entry(t,width=30,bg='orange')
        e6.place(x=1100,y=455)
        b2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
        b2.place(x=1000,y=500)
        b3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
        b3.place(x=1100,y=500)
def update5():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        s=e4.get()
        t=e5.get()
        u=int(e6.get())
        sql="update orders set Customer_ID='%s',Item_ID='%s',ItemCategoryID='%s',Date_Order='%s',Qty=%d where OrderID='%s'"%(q,r,s,t,u,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Customer_ID,Item_ID,ItemCategoryID,Date_Order,Qty from orders where OrderID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        e5.insert(0,str(data[3]))
        e6.insert(0,str(data[4]))
        x.close()
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        s=e4.get()
        t=e5.get()
        u=int(e6.get())
        sql="update orders set Customer_ID='%s',Item_ID='%s',ItemCategoryID='%s',Date_Order='%s',Qty=%d where OrderID='%s'"%(q,r,s,t,u,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Customer_ID,Item_ID,ItemCategoryID,Date_Order,Qty from orders where OrderID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        e5.insert(0,str(data[3]))
        e6.insert(0,str(data[4]))
        x.close()
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=205)
    l2=Label(t,text='Customer Id',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1100,y=255)
    l3=Label(t,text='Item Id',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1100,y=305)
    l4=Label(t,text='Item Category Id',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1100,y=355)
    l5=Label(t,text='Date Of Order',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=30,bg='orange')
    e5.place(x=1100,y=405)
    l6=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=30,bg='orange')
    e6.place(x=1100,y=455)
    b4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b4.place(x=1350,y=200)
    b5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    b5.place(x=1050,y=500)
def delete5():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="delete from orders where OrderID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        e1.delete(0,100)
        x.close()
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=950,y=290)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=295)
    b6=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    b6.place(x=1050,y=350)
def insert6():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        w=e4.get()
        t=int(e5.get())
        u=int(e6.get())
        v=int(e7.get())
        sql="insert into Bill values('%s','%s','%s','%s',%d,%d,%d)"%(p,q,r,w,t,u,v)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        e7.delete(0,100)
        x.close()
    def total():
        t=int(e5.get())
        u=int(e6.get())
        to=t*u
        e7.insert(0,to)
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1150,y=205)
    l2=Label(t,text='Customer Id',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1150,y=255)
    l3=Label(t,text='Bill Id',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1150,y=305)
    l4=Label(t,text='Item id',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1150,y=355)
    l5=Label(t,text='Price',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=30,bg='orange')
    e5.place(x=1150,y=405)
    l6=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=30,bg='orange')
    e6.place(x=1150,y=455)
    l7=Button(t,text='Total',fg='black',font=('Elephant',13),bg='orange',command=total)
    l7.place(x=1350,y=495)
    e7=Entry(t,width=30,bg='orange')
    e7.place(x=1150,y=505)
    b1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert)
    b1.place(x=1100,y=560)
def find6():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Customer_ID,Bill_ID,Item_ID,Price_per_piece,Quantity,Total_Bill from bill where OrderID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        e5.insert(0,str(data[3]))
        e6.insert(0,str(data[4]))
        e7.insert(0,str(data[5]))
        x.close()
    def reset():
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        e7.delete(0,100)
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1150,y=205)
    l2=Label(t,text='Customer Id',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1150,y=255)
    l3=Label(t,text='Bill Id',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1150,y=305)
    l4=Label(t,text='Item id',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1150,y=355)
    l5=Label(t,text='Price',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=30,bg='orange')
    e5.place(x=1150,y=405)
    l6=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=30,bg='orange')
    e6.place(x=1150,y=455)
    l7=Label(t,text='Total',fg='black',font=('Elephant',15),bg='white')
    l7.place(x=900,y=500)
    e7=Entry(t,width=30,bg='orange')
    e7.place(x=1150,y=505)
    b2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b2.place(x=1050,y=560)
    b3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    b3.place(x=1150,y=560)
def update6():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        w=e4.get()
        t=int(e5.get())
        u=int(e6.get())
        v=int(e7.get())
        sql="update Bill set Customer_ID='%s',bill_ID='%s',Item_ID='%s',Price_per_piece=%d,Quantity=%d,Total_Bill=%d where OrderID='%s'"%(q,r,w,t,u,v,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        e5.delete(0,100)
        e6.delete(0,100)
        e7.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Customer_ID,Bill_ID,Item_ID,Price_per_piece,Quantity,Total_Bill from bill where OrderID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        e5.insert(0,str(data[3]))
        e6.insert(0,str(data[4]))
        e7.insert(0,str(data[5]))
        x.close()
    def total():
        e7.delete(0,100)
        t=int(e5.get())
        u=int(e6.get())
        to=t*u
        e7.insert(0,to)
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=200)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1150,y=205)
    l2=Label(t,text='Customer Id',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=250)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1150,y=255)
    l3=Label(t,text='Bill Id',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=300)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1150,y=305)
    l4=Label(t,text='Item id',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=350)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1150,y=355)
    l5=Label(t,text='Price',fg='black',font=('Elephant',15),bg='white')
    l5.place(x=900,y=400)
    e5=Entry(t,width=30,bg='orange')
    e5.place(x=1150,y=405)
    l6=Label(t,text='Quantity',fg='black',font=('Elephant',15),bg='white')
    l6.place(x=900,y=450)
    e6=Entry(t,width=30,bg='orange')
    e6.place(x=1150,y=455)
    l7=Button(t,text='Total',fg='black',font=('Elephant',13),bg='orange',command=total)
    l7.place(x=1350,y=495)
    e7=Entry(t,width=30,bg='orange')
    e7.place(x=1150,y=505)
    b4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b4.place(x=1350,y=190)
    b5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    b5.place(x=1050,y=560)
def delete6():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="delete from Bill where OrderID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        e1.delete(0,100)
        x.close()
    l1=Label(t,text='Order ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=950,y=290)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=295)
    b6=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    b6.place(x=1050,y=350)
def insert7():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def insert():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        s=e4.get()
        sql="insert into dispatch values('%s','%s','%s','%s')"%(p,q,r,s)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Saved','Data Saved')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        x.close()
    l1=Label(t,text='Dispatch ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=250)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1150,y=255)
    l2=Label(t,text='Bill ID',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=300)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1150,y=305)
    l3=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=350)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1150,y=355)
    l4=Label(t,text='Date Of Delivery',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=400)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1150,y=405)
    b1=Button(t,text='Insert',fg='black',font=('Elephant',15),bg='orange',command=insert)
    b1.place(x=1050,y=460)
def find7():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Bill_ID,Customer_ID,Date_Of_Delivery from dispatch where Dispatch_ID='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        x.close()
    def reset():
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
    l1=Label(t,text='Dispatch ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=250)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1150,y=255)
    l2=Label(t,text='Bill ID',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=300)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1150,y=305)
    l3=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=350)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1150,y=355)
    l4=Label(t,text='Date Of Delivery',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=400)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1150,y=405)
    b2=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b2.place(x=1050,y=450)
    b3=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    b3.place(x=1155,y=450)
def update7():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def update():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        q=e2.get()
        r=e3.get()
        s=e4.get()
        sql="update dispatch set Bill_ID='%s',Customer_ID='%s',Date_Of_Delivery='%s' where Dispatch_ID='%s'"%(q,r,s,p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Updated','Data Updated')
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
        x.close()
    def find():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="select Bill_ID ,Customer_ID,Date_Of_Delivery from dispatch where Dispatch_ID ='%s'"%(p)
        y.execute(sql)
        data=y.fetchone()
        e2.insert(0,data[0])
        e3.insert(0,data[1])
        e4.insert(0,data[2])
        x.close()
    def reset():
        e1.delete(0,100)
        e2.delete(0,100)
        e3.delete(0,100)
        e4.delete(0,100)
    l1=Label(t,text='Dispatch ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=900,y=250)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1150,y=255)
    l2=Label(t,text='Bill ID',fg='black',font=('Elephant',15),bg='white')
    l2.place(x=900,y=300)
    e2=Entry(t,width=30,bg='orange')
    e2.place(x=1150,y=305)
    l3=Label(t,text='Customer ID',fg='black',font=('Elephant',15),bg='white')
    l3.place(x=900,y=350)
    e3=Entry(t,width=30,bg='orange')
    e3.place(x=1150,y=355)
    l4=Label(t,text='Date Of Delivery',fg='black',font=('Elephant',15),bg='white')
    l4.place(x=900,y=400)
    e4=Entry(t,width=30,bg='orange')
    e4.place(x=1150,y=405)
    b4=Button(t,text='Find',fg='black',font=('Elephant',15),bg='orange',command=find)
    b4.place(x=1350,y=230)
    b5=Button(t,text='Update',fg='black',font=('Elephant',15),bg='orange',command=update)
    b5.place(x=1050,y=450)
    b6=Button(t,text='Reset',fg='black',font=('Elephant',15),bg='orange',command=reset)
    b6.place(x=1150,y=450)
def delete7():
    import pymysql
    c=Canvas(t,width=700,height=600,bg='white')
    c.place(x=770,y=60)
    def delete():
        x=pymysql.connect(host='localhost',user='root',password='root',database='stockmarket')
        y=x.cursor()
        p=e1.get()
        sql="delete from dispatch where Dispatch_ID='%s'"%(p)
        y.execute(sql)
        x.commit()
        messagebox.showinfo('Deleted','Data Deleted')
        e1.delete(0,100)
        x.close()
    l1=Label(t,text='Dispatch ID',fg='black',font=('Elephant',15),bg='white')
    l1.place(x=950,y=290)
    e1=Entry(t,width=30,bg='orange')
    e1.place(x=1100,y=295)
    b6=Button(t,text='Delete',fg='black',font=('Elephant',15),bg='orange',command=delete)
    b6.place(x=1050,y=350)